### ISSUE TITLE
How to refer to an id that does not exist yet (how to make compoment based web-development possible)

### ISSUE THREAD

**Issue by dionverbeke** [cferdinandi/reef#134]
How can you enable component based web development with Reef? 
I think the attachTo to is a good start. But I have difficulty understanding 
where to inject the javascript code cleanly.

An example to follow:

mapid is created in the component. I now get an error that mapid does not exist yet.
Ideally I would like to be able to fix the html part and then apply the javascript part.

HTML:

```html
<div id="filter"></div>
```

CSS:

```css
#filter {
min-height:200px;
}
```

JS:

```js
var filter = new Reef('#filter', {
    data: {
        greeting: 'Hello',
        name: 'world'
    },
    template: function (props) {
        var mymap = L.map('mapid').setView([51.505, -0.09], 13);
        L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            maxZoom: 18,
            id: 'mapbox/streets-v11',
            tileSize: 512,
            zoomOffset: -1,
            accessToken: 'xyz'
        }).addTo(mymap);
        let a = [{x:51.5,y:-0.09},{x:51.5,y:-0.091},{x:51.5,y:-0.092},{x:51.5,y:-0.093    },{x:51.5,y:-0.10},{x:51.5,y:-0.11},{x:51.5,y:-0.12},{x:51.5,y:-0.13},{x:51.5,y:-1.09},{x:51.5,y:-2.09},{x:51.5,y:-3.09},];
        a.forEach(function(element, i) {
            L.marker([element.x, element.y]).addTo(mymap);
        });
        return <h1>${props.greeting},${props.name}</h1><div id="mapid"></div>;
    }
});
```

**Comment by cferdinandi** [comment]
Hi @dionverbeke - I see what you're trying to do here. To be honest, if the mapbox API is being used to generate the map here, I'd do one of two things...

1. Just hard code your HTML into the UI instead of using Reef. I see little benefit to this approach here, and a huge likelihood that your HTML gets wiped out unexpectedly when the component updates.
2. [Use an event listener](https://reefjs.com/api/#events) to run your mapbox code _after_ the component renders. In the latest ReefJS, that's the `reef:render` event, but in previous versions it was the `render` event.

Option 1 probably makes more sense here...
