### ISSUE TITLE
Listen to nested subcomponent render

### ISSUE THREAD

**Issue by Falkan3** [cferdinandi/reef#140]
Hello, first of all, thanks for the awesome work.

I'm developing a plugin using reef as a reactive UI renderer, and I have a nested component structure like so:
```
App->Component
```
The component is attached to App. 
I want to bind to Component's render event to create a carousel inside it after it has been rendered. So far I've only found the base `reef:render` which is fired every time any template has been rendered, and results in errors because the Component has not rendered any html yet.
How would I go about waiting for a specific template to finish rendering?
I tried comparing `reef:render` event target but to no avail (it is also called every time even if the template is not going to be rendered).

Kind regards

**Comment by cferdinandi** [comment]
@Falkan3 Apologies, as I'm a bit confused here.

The `reef:render` event event fires _on a specific element_ whenever that element's content is re-rendered, and bubbles up to the `window` or `document` (just like other events like `click` do). 

You can attach you event listener directly to the element you want to listen for renders inside.

```js
let elem = document.querySelector('.my-carousel');
elem.addEventListener('reef:render', function (event) {
    console.log('The carousel was rendered!');
});
```

**Historically**, this was more complicated with nested components because the original element might get purged from the DOM, breaking the event listener, so I would recommend [event delegation](https://gomakethings.com/why-event-delegation-is-a-better-way-to-listen-for-events-in-vanilla-js/).

**Today**, you can now [attach event listeners on specific elements using `on*` attributes in your template](https://reefjs.com/advanced/#attaching-event-listeners-to-elements). Reef uses event delegation under-the-hood, and automatically handles when elements get added or removed from the DOM.

```js
new Reef('#app', {
	data: {
		heading: 'Hello, world!'
	},
	template: function (props) {
		return `
			<h1>${props.heading}</h1>
			<div id="sub-component" onreef:render="onrender">
				${subcomponent.html()}
			</div>`;
	},
	listeners: {
		onrender: function (event) {
			// do something...
		}
	}
}).render();
```

**Comment by Falkan3** [comment]
Thank you, I was looking for the nested component delegation as the element was being purged every time the parent rerendered, as the HTML was dynamic and the nested component looked for the presence of nested elements to initialize.

**Comment by cferdinandi** [comment]
Awesome. This works?

**Comment by Falkan3** [comment]
Hello, unfortunately it doesn't seem to be working. I am using version 11.0.1. I set a breakpoint to test if the listener function is being called, and it's not.
![image](https://user-images.githubusercontent.com/15730072/146949784-6e0dab36-d18f-4cd2-97fe-9a200780be42.png)

**Comment by Falkan3** [comment]
Hello, unfortunately it doesn't seem to be working. I'm using version 11.0.1. Could it be because the subcomponent HTML root is dynamic? I'm setting the html on the parent component using the data, looping through an array and appending the HTML, then waiting for the parent to render, and finally creating a Reef subcomponent for each root in the final HTML.

**Comment by cferdinandi** [comment]
So, in your example there, you're creating a new `Reef()` instance as your event callback function.

What exactly are you trying to do?

**Comment by Falkan3** [comment]
Perhaps I'm misunderstanding, I want to create a new Reef component using elements in the parent's HTML, so that they are nested. I want to have a Reef instance for parent, and an instance for each subcomponent inside the parent. I'm certain there is a better way to do this.

**Comment by cferdinandi** [comment]
Gotcha. And you've seen this: https://reefjs.com/advanced/#nested-components

**Comment by Falkan3** [comment]
Yes, I'm familiar with the docs. Perhaps my issue is with the dynamic selector, in your example it is static and known beforehand. In my case each ID for the subcomponent is unique.

**Comment by Falkan3** [comment]
It makes sense, I will try to simplify the logic, I separated the components because I wanted the code to me more modular and load on demand. Thank you for your time anyways.
