### ISSUE TITLE
onclick attributes sanitized out

### ISSUE THREAD

**Issue by everdev** [cferdinandi/reef#16]
First off, thanks for creating a frontend UI library I actually enjoy using :)

Picked it up in about 30min following the great documentation and it'll work for most of my projects.

The potential bug I found is here (onclick attributes being stripped on data updates): https://codepen.io/anon/pen/WPPZjB

To reproduce:

1. Click the heading multiple times to see the timestamp update
2. Uncomment the `Reef.setSanitizer` function
3. Click the heading multiple times to see the timestamp only update once

Maybe it's similar to issues #12 & #9 ?

**Comment by cferdinandi** [comment]
That's expected behavior. `onclick` is considered unsafe by DOMPurify, as it can leave you vulnerable to XSS attacks, so it's stripped out.

I'd recommend using `addEventListener()` to detect clicks on that element instead.

You could also consider passing only properties into DOMPurify instead of your entire markup.

**Comment by cferdinandi** [comment]
Oh, and...

> First off, thanks for creating a frontend UI library I actually enjoy using :)

You're welcome!

**Comment by cferdinandi** [comment]
Had a change of heart on this. Fixed with https://github.com/cferdinandi/reef/releases/tag/v4.1.7
