### ISSUE TITLE
Valid HTML5 custom elements render once but do not update

### ISSUE THREAD

**Issue by arthurdent** [cferdinandi/reef#206]
https://github.com/cferdinandi/reef/blob/master/src/components/render.js#L347

This code seems to make the assumption that one would never want to diff inside of a custom element / web component, but it's unclear to me why this assumption is made. This behavior was unexpected and took quite a bit of time to identify.

**Test case:** https://codepen.io/_x2a/pen/mdZrZoo

**Comment by cferdinandi** [comment]
Yes, that's very much by design. Web Components handle their own state internally, and should not be differed by state-based UI libaries.

**Comment by cferdinandi** [comment]
Yes, that's very much by design. Web Components handle their own state internally, and should not be differed by state-based UI libraries.

That's documented here: https://reefjs.com/advanced/web-components/#in-templates

You can use Reef _inside_ your Web Component for Reactivity, though, if desired: https://reefjs.com/advanced/web-components/#reactive-web-components
