### ISSUE TITLE
Doesn't render <td> and <tr> HTML elements when selecting by class name

### ISSUE THREAD

**Issue by konrad-g** [cferdinandi/reef#22]
For some reason `<td>` and `<tr>` elements are not being rendered when returned from template function.

It happened when I tried to use Reef to render the content of `<tbody>` only, using a class selector. Once I tried to render the whole table structure, it worked well.

Working example: 
https://codepen.io/konrad-g-the-flexboxer/pen/KKPrxPj

**Comment by cferdinandi** [comment]
I was able to get this figured out. This is happening because of how the template string is converted into HTML behind the scenes. Your table elements outside of a `tbody` or `thead` are treated as invalid and converted to text, stripping out all of the markup around them.

If you remove the existing content from your `thead`, Reef will understand that they're going into a valid element and render it correctly. Otherwise, this specific setup just won't work.
