### ISSUE TITLE
domParser performance 

### ISSUE THREAD

**Issue by geoffgscott** [cferdinandi/reef#32]
Consider switching from domParser to document.createRange().createContextualFragment() on modern browsers. 

With small html strings the performance increases are quite large. The attached test shows createContextualFragment completing in around 10% of the time it takes domParser. 

For large test strings (like an entire webpage) there is smaller but still significant gains (createContextualFragment completing in 65-85% of the of the time it takes domParser).

(all numbers from chrome 79). 
 
https://jsperf.com/html-string-to-dom-node

**Comment by cferdinandi** [comment]
Document fragments are great, but there's no way to get the fragment content and work with it prior to injecting it into an element (which has performance implications of its own).

If Reef were just wholesale overwriting the DOM, this would be an awesome approach. However, since Reef has to loop through and _diff_ the current UI against the desired one, this is not an ideal option for this project.

I am concerned about performance, though. I'd like to see an alternate version of these tests where the generated HTML is more than just a "Hello world." Maybe some nested HTML elements with list items or something. 

Doing some simple math on the numbers the test provided, in the latest Chrome, Reef is generating the UI in a fraction of a millisecond. Even though the fragment may be faster, I'd hardly call that "bad for performance."

**Comment by cferdinandi** [comment]
I am very open to hearing your thoughts on this, btw!

**Comment by geoffgscott** [comment]
Hmm. You could probably domMap the fragment and then compare but I am sure that is cutting into the performance advantages.

 Also worth noting the document fragments will run scripts and would need some string sanitation which again will start to negate any speed advantages.

**Comment by cferdinandi** [comment]
Also not ideal. This feels to me like an "it depends" kind of thing, where fragments are great at certain tasks, but not the one we're trying to accomplish with this script.

**Comment by cferdinandi** [comment]
Closing this since I think I'm going to keep things as-is for now.
