### ISSUE TITLE
Access public variables of a class

### ISSUE THREAD

**Issue by DaviUchoa** [cferdinandi/reef#63]
**Test Case** https://codepen.io/daviuchoa/pen/jOWKNZX?editors=1010

Hi, 

I'm using a simple class with a public instance variable called `name` and setting the class to the state. But a strange behavior occur when the method `render()`  is fired, the access of the `name` results in an error. 

But if I comment the `render()` and after that set the state, it works.

Thanks in advance.

**Comment by cferdinandi** [comment]
There seems to be some confusion on your end about how classes work.

The `Hero` class doesn't automatically get mapped to `app.data.hero`. When you run `app.render()`, `props.hero` has a value of `null`, because that's what you defined it as when setting up your component.

When you explicitly set `app.data.hero` to the output of `new Hero('Iron Man')`, you've now given it a value. The data update triggers a UI updates (because the data is reactive), and the UI updates with the new value.

**Comment by DaviUchoa** [comment]
You're right, I forgot about the reactivity concept in this case. 

Thanks for the clarifications
