### ISSUE TITLE
Understanding the router 

### ISSUE THREAD

**Issue by fictorial** [cferdinandi/reef#77]
Hi, I don't see an easy way to contact you with a question. This isn't an issue really. Sorry for the intrusion.

I am having a bit of a time understanding why a route would be associated with multiple components instead of just one.  Could you clue me in on the rationale?  Nested routes perhaps?

Thanks.  BTW, I'm loving the minimalism of this project. It's refreshing.

**Comment by cferdinandi** [comment]
A page could have multiple components on it, and each one could have content that's route dependent.

**Comment by ecanuto** [comment]
Maybe, just like me he wants to show/hide components based on route. Is there any easy way to do it on Router class?

**Comment by cferdinandi** [comment]
@ecanuto There are two ways to do that...

In the `template`, you have access to the `route` details.

```js
var app = new Reef('#app', {
	router: router,
	data: {
		greeting: 'hello!'
	},
	template: function (props, route) {
		return `
			<h1>${route.title}</h1>
			<p>${props.greeting}</p>`;
	}
});
```

You can check the `route.id`, or some other related information, and return a different template depending on what it is:

```js
var app = new Reef('#app', {
	router: router,
	data: {
		greeting: 'hello!'
	},
	template: function (props, route) {
		if (route.id === 'home' ) {
			return 'home';
		} else {
			return 'not home';
		}
	}
});
```

Alternatively, you can attach the same router to multiple components, and return an empty string when the component isn't for the current route. I personally prefer this second approach because it keeps each template modularized and bakes in a lot of logic for you.

**Comment by ecanuto** [comment]
Thank you @cferdinandi. Btw, just start to use your framework yesterday but it looks so "right" ;-)
Congrats by so amazing work!
