### ISSUE TITLE
Issue clearing input with value=""

### ISSUE THREAD

**Issue by slynn1324** [cferdinandi/reef#88]
I'm likely missing something as it seems that this would be a common case -- and if so direction is appreciated. 

Thanks!

Test Case:
https://codepen.io/slynn1324/pen/eYdoYjM

**Comment by slynn1324** [comment]
I don't know if you would be interested, but I think I have hacked together input data-binding support.  There would certainly be better ways to bootstrap this if fully integrated into the framework.

Current limitations:
- binding to non-store data
- detecting child reef elements.  currently, this simply looks for all `[data-bind]` elements inside of the bound reef element, so it will find elements inside of a child reef - but it doesn't know which reef context they belong to - which relates back to point 1. 
- only tested in chrome

https://codepen.io/slynn1324/pen/rNMbvPE

**Comment by cferdinandi** [comment]
This is definitely a bug, caused by a decision I made a while ago to ignore `value=""` on inputs because all inputs have a value property even if one isn't explicitly defined and it was causing unintended side effects.

I'm sure there's a way around this, I just don't know what it is yes. I'll look into it.

**Comment by cferdinandi** [comment]
This should be fixed with v7.6.6. Let me know if it's not working as expected for you, though!

**Comment by cferdinandi** [comment]
Demo here: https://codepen.io/cferdinandi/pen/ExgzNON
